# Generated by Django 3.2.5 on 2021-12-25 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContatactedPersons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('tc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('city', models.CharField(max_length=30)),
                ('pos', models.CharField(blank=True, max_length=30, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hobbies', models.TextField(null=True)),
                ('level_of_education', models.CharField(choices=[('undergraduate', 'undergraduate'), ('masters', 'masters'), ('doctorate', 'doctorate')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('pcode', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('title', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=32)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('p', models.ManyToManyField(to='base.Prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('dcode', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=30)),
                ('date_of_disease', models.DateField()),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.prescription')),
                ('symptoms', models.ManyToManyField(blank=True, to='base.Symptom')),
            ],
        ),
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_date', models.DateField()),
                ('n_date', models.DateField()),
                ('vaccinated', models.BooleanField()),
                ('vaccine', models.CharField(blank=True, max_length=30, null=True)),
                ('doz', models.IntegerField(blank=True, null=True)),
                ('chronic_d', models.CharField(blank=True, max_length=30)),
                ('contacted_persons', models.ManyToManyField(blank=True, to='base.ContatactedPersons')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
                ('symptoms', models.ManyToManyField(to='base.Symptom')),
            ],
        ),
        migrations.AddField(
            model_name='contatactedpersons',
            name='em',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee'),
        ),
    ]
