# Generated by Django 3.2.5 on 2021-12-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicDisease',
            fields=[
                ('title', models.CharField(max_length=60, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='covid',
            name='chronic_d',
        ),
        migrations.AlterField(
            model_name='covid',
            name='symptoms',
            field=models.ManyToManyField(blank=True, to='base.Symptom'),
        ),
        migrations.AddField(
            model_name='covid',
            name='ch_d',
            field=models.ManyToManyField(blank=True, null=True, to='base.ChronicDisease'),
        ),
    ]
