# Generated by Django 3.2.5 on 2021-12-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211225_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContatactedPersons',
            new_name='ContactedPersons',
        ),
        migrations.RemoveField(
            model_name='covid',
            name='ch_d',
        ),
        migrations.AddField(
            model_name='covid',
            name='cd',
            field=models.ManyToManyField(blank=True, to='base.ChronicDisease'),
        ),
    ]
