# Generated by Django 3.2.5 on 2021-12-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211225_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroupCovidFreq',
            fields=[
                ('blood_group', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('covid_freq', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'blood_group_covid_freq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CityCommonDisease',
            fields=[
                ('city', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=30)),
                ('d_count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'city_common_diseases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CovidEmpWorkingHoursStat',
            fields=[
                ('hours_per_week', models.DecimalField(decimal_places=2, max_digits=5, primary_key=True, serialize=False)),
                ('num_of_emps', models.BigIntegerField()),
            ],
            options={
                'db_table': 'covid_emp_working_hours_stat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EduCovidStat',
            fields=[
                ('level_of_education', models.CharField(choices=[('undergraduate', 'undergraduate'), ('masters', 'masters'), ('doctorate', 'doctorate')], max_length=30, primary_key=True, serialize=False)),
                ('mycount', models.BigIntegerField()),
            ],
            options={
                'db_table': 'edu_covid_stat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MostCommonDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=30)),
                ('d_count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'most_common_disease',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MostCommonDiseaseEmp',
            fields=[
                ('tc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'most_common_disease_emp',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='covid',
            name='vaccine',
        ),
        migrations.AddField(
            model_name='covid',
            name='vaccine_type',
            field=models.CharField(blank=True, choices=[('biontech', 'biontec'), ('sinovac', 'sinovac')], max_length=30, null=True),
        ),
    ]
