# Generated by Django 3.2.5 on 2021-12-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211225_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiontechCovidEmp',
            fields=[
                ('total_time', models.DecimalField(decimal_places=2, max_digits=6, primary_key=True, serialize=False)),
                ('num_of_emps', models.BigIntegerField()),
            ],
            options={
                'db_table': 'biontech_covid_emps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MostCommonCovidSymptom',
            fields=[
                ('symptom', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('symptom_count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'most_common_covid_symptoms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MostContactedPerson',
            fields=[
                ('tc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('contact_count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'most_contacted_persons_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MostFreqillEmp',
            fields=[
                ('tc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('disease_count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'most_freq_ill_emps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MostFreqillEmpsCovid',
            fields=[
                ('tc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'most_freq_ill_emps_covid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NonVaccinatedEmp',
            fields=[
                ('tc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('covid_d', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'non_vaccinated_emp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NonVaccinatedEmpDisPre',
            fields=[
                ('dname', models.CharField(max_length=30)),
                ('prescription_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'non_vaccinated_emp_diseases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SinovacCovidEmp',
            fields=[
                ('total_time', models.DecimalField(decimal_places=2, max_digits=6, primary_key=True, serialize=False)),
                ('num_of_emps', models.BigIntegerField()),
            ],
            options={
                'db_table': 'sinovac_covid_emps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeekendsWorker',
            fields=[
                ('tc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'weekends_workers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeekendsWorkersCovid',
            fields=[
                ('tc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'weekends_workers_covid',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='covid',
            name='vaccine_type',
            field=models.CharField(blank=True, choices=[('biontech', 'biontech'), ('sinovac', 'sinovac')], max_length=30, null=True),
        ),
    ]
