# Generated by Django 3.2.5 on 2021-12-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211227_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostCommonlyUsedDrug',
            fields=[
                ('dname', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('d_count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'most_common_drugs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MostCommonlyUsedDrugsUser',
            fields=[
                ('tc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'most_common_drugs_users',
                'managed': False,
            },
        ),
    ]
