# Generated by Django 3.2.5 on 2021-12-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_mostcommonlyuseddrug_mostcommonlyuseddrugsuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='p',
        ),
        migrations.AddField(
            model_name='prescription',
            name='drugs',
            field=models.ManyToManyField(blank=True, to='base.Drug'),
        ),
    ]
